use mattLoam;

drop table bookings;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    fullName VARCHAR(255) NOT NULL,
    role ENUM("admin", "user") DEFAULT "user",
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    originalName VARCHAR(500) NOT NULL,
    fileName VARCHAR(500) UNIQUE NOT NULL,
    path VARCHAR(100) NOT NULL,
    mimeType VARCHAR(100) NOT NULL,
    size INT NOT NULL,

    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
);